pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            // Automatically resolve the Android Library plugin version safely
            if (requested.id.id == 'com.android.library') {
                useModule('com.android.tools.build:gradle:8.2.2')
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'holomatics-sdk'
include ':library'
